### ISSUE TITLE
minor netedit ux-enhancements

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#10426]
- [x] Creating a **New Network** should not display `Reload sucesfully` in the *Message Window*
- [x] The `Show undo/redo history` option should be **disabled** if there are no elements to show (just as in `Undo` and `Redo`)
- [x] The `Save TLS Programs` and `Save Edge Types` options should be initially disabled, ~leaving (at first) only "Save As..." possible (just as in *Save Additionals*, *Save Demand Elements* and *Save Data Elements*)~
- [x] Disable `Save As...` options until there is actually something to save (Additionals, Demand Elements and Data Elements)
- [x] Remove the divider in the `Processing` menu (in **Data mode**) - there is only one menu item ("Options")
- [x] Add a `Reload` option to "**Traffic Lights**" and "**Edge Types**" - for consistency sake
- [x] Rename the "Windows" menu bar element to "Window" (or "View") (in **sumo-gui** too)
- [x] Show *Traffic Lights*, *Edge Types*, *Additionals and Shapes*, *Demand Elements* and *Data Elements* disabled by default when opening netedit with no network. These options should only be clickable if a net is loaded, or the user selected "New Network"
- [x] The new `Draw function shape` checkbox should also show/hide the red bubbles for small junctions
- [x] Rephrase checkbox-options in the **Edit** menu to avoid the use of the word "Toggle": having the checkboxes and check marks is more than enough
- [x] Have the same default "Zoomstyle" behavior for both sumo-gui and netedit (its currently not the case)
