### ISSUE TITLE
Implement GNETLSTable

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#11241]
The new GNETLSTable is based on lists of FXTextFields, FXLabels and FXButtons and is the best solution for the following tickets:

- [x] #11282 -> Now with tabulators phase buttons can be reach

- [x] #11240 -> Not anymore

- [x] #11149 -> Now if no TLS are selected, a default width is set

- [x] #10856 -> New buttons for add/delete phase in every row

**Comment by namdre** [comment]
also solves #2035

**Comment by palvarezlopez** [comment]
GNETLSTable is 100% functional. New problems will be handled in different tickets.
