### ISSUE TITLE
make --language a proper meta option

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12681]
- [ ] It should not trigger "missing network" etc. errors
- [ ] It should affect all parameter option help outputs (`--help`, `--save-template`)
- [ ] the display language in sumo-gui / netedit should change if called with only --language

**Comment by m-kro** [comment]
@behrisch With the changes currently translated items are printed in the language chosen with **--language**. Maybe check if I got something wrong or if there is a better way. I think the help section titles and other stuff from the help output still need to be made translatable, right?
