### ISSUE TITLE
implement icons for pois

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#13721]
This requires:
- [ ] Introduce new `icon` attribute for POI-elements: #13718
- [ ] Offer diverse default poi-icons: #13719
- [ ] While importing OSM networks, parse and use these icons for certain types of pois: #13720
