### ISSUE TITLE
small Phase tracker issues

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9963]
- [x] phases with identical states are merged
- [x] names of phases run into each other (repeated names should be skipped)
- [x] green duration is split when phase changes even on a continuous green bar. Should optional be switched to showing aggregated green duration
